/*
 * File: app/store/NestedTopics.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fihrist.store.NestedTopics', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'Fihrist.model.Nested'
    ],

    config: {
        autoLoad: true,
        data: {
            text: 'Groceries',
            items: [
                {
                    text: 'acı',
                    items: [
                        {
                            text: 'yozlaşmış bir dünyanın sonucu',
                            items: [
                                {
                                    text: 'ROMALILAR 8:18-22',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Rom8_18-22.mp3',
                                    vtext: 'ROMALILAR 8:18-22 (TCL02)<br/><br/>Kanım şu ki, bu anın acıları, gözümüzün önüne serilecek yücelikle karşılaştırılmaya değmez. Yaratılış, Tanrı çocuklarının ortaya çıkmasını büyük özlemle bekliyor. Çünkü yaratılış amaçsızlığa teslim edildi. Bu da yaratılışın isteğiyle değil, onu amaçsızlığa teslim eden Tanrı nın isteğiyle oldu. Çünkü yaratılışın, yozlaşmaya köle olmaktan kurtarılıp Tanrı çocuklarının yüce özgürlüğüne kavuşturulması umudu vardı.',
                                    leaf: true
                                },
                                {
                                    text: 'Still',
                                    url: 'some other url',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'Coffee',
                            leaf: true
                        },
                        {
                            text: 'Espresso',
                            leaf: true
                        },
                        {
                            text: 'Redbull',
                            leaf: true
                        },
                        {
                            text: 'Coke',
                            leaf: true
                        },
                        {
                            text: 'Diet Coke',
                            leaf: true
                        }
                    ]
                },
                {
                    text: 'Fruit',
                    items: [
                        {
                            text: 'Bananas',
                            leaf: true
                        },
                        {
                            text: 'Lemon',
                            leaf: true
                        }
                    ]
                },
                {
                    text: 'Snacks',
                    items: [
                        {
                            text: 'Nuts',
                            leaf: true
                        },
                        {
                            text: 'Pretzels',
                            leaf: true
                        },
                        {
                            text: 'Wasabi Peas',
                            leaf: true
                        }
                    ]
                }
            ]
        },
        model: 'Fihrist.model.Nested',
        storeId: 'NestedTopics',
        defaultRootProperty: 'items'
    }
});