/*
 * File: app/store/NestedTopics.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fihrist.store.NestedTopics', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'Fihrist.model.Nested'
    ],

    config: {
        autoLoad: true,
        data: {
            items: [
                {
                    text: 'acı',
                    items: [
                        {
                            text: 'yozlaşmış bir dünyanın sonucu',
                            items: [
                                {
                                    text: 'ROMALILAR 8:18-22',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Rom8_18-22.mp3',
                                    vtext: 'ROMALILAR 8:18-22 (TCL02)<br/><br/>Kanım şu ki, bu anın acıları, gözümüzün önüne serilecek yücelikle karşılaştırılmaya değmez. Yaratılış, Tanrı çocuklarının ortaya çıkmasını büyük özlemle bekliyor. Çünkü yaratılış amaçsızlığa teslim edildi. Bu da yaratılışın isteğiyle değil, onu amaçsızlığa teslim eden Tanrı nın isteğiyle oldu. Çünkü yaratılışın, yozlaşmaya köle olmaktan kurtarılıp Tanrı çocuklarının yüce özgürlüğüne kavuşturulması umudu vardı.',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'genellikle ceza değil',
                            items: [
                                {
                                    text: 'Luk.13:1-5',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Luk13_1-5.mp3',
                                    vtext: 'LUKA 13:1-5 (TCL02)<br/><br/>O sırada bazı kişiler gelip İsa\'ya bir haber getirdiler. Pilatus\'un nasıl bazı Celileliler\'i öldürüp kanlarını kendi kestikleri kurbanların kanına kattığını anlattılar. İsa onlara şöyle karşılık verdi: “Böyle acı çeken bu Celileliler\'in, bütün öbür Celileliler\'den daha günahlı olduğunu mu sanıyorsunuz? Size hayır diyorum. Ama tövbe etmezseniz, hepiniz böyle mahvolacaksınız.',
                                    leaf: true
                                },
                                {
                                    text: 'Yuh.9:1-3',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Yuh9_1-3.mp3',
                                    vtext: 'Scripture verse missing',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'amacı, sonuçları:',
                            items: [
                                {
                                    text: 'Rom.5:3-5',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Rom5_3-5.mp3',
                                    vtext: 'ROMALILAR 5:3-5 (TCL02)<br/><br/>Yalnız bununla değil, sıkıntılarla da övünüyoruz. Çünkü biliyoruz ki, sıkıntı dayanma gücünü, dayanma gücü Tanrı\'nın beğenisini, Tanrı\'nın beğenisi de umudu yaratır. Umut düş kırıklığına uğratmaz. Çünkü bize verilen Kutsal Ruh aracılığıyla Tanrı\'nın sevgisi yüreklerimize dökülmüştür.',
                                    leaf: true
                                },
                                {
                                    text: 'Yak.1:2-4',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Yak1_2-4.mp3',
                                    vtext: 'YAKUP 1:2-4 (TCL02)<br/><br/>Kardeşlerim, çeşitli denemelerle yüz yüze geldiğinizde bunu büyük sevinçle karşılayın. Çünkü bilirsiniz ki, imanınızın sınanması dayanma gücünü yaratır. Dayanma gücü de, hiçbir eksiği olmayan, olgun, yetkin kişiler olmanız için tam bir etkinliğe erişsin.',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'Acı çekerken RAB\'be güvenmek:',
                            items: [
                                {
                                    text: '2Ko.1:3-11',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/2Ko1_3-11.mp3',
                                    vtext: '2.KORİNTLİLER 1:3-11 (TCL02)<br/><br/>Her türlü tesellinin kaynağı olan Tanrı\'ya, merhametli Baba\'ya, Rabbimiz İsa Mesih\'in Tanrısı ve Babası\'na övgüler olsun! Kendisinden aldığımız teselliyle her türlü sıkıntıda olanları teselli edebilmemiz için bizi bütün sıkıntılarımızda teselli ediyor. Çünkü Mesih\'in acılarını nasıl büyük ölçüde çekiyorsak, Mesih sayesinde büyük teselli de buluyoruz.',
                                    leaf: true
                                },
                                {
                                    text: 'Rom.8:28',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Rom8_28.mp3',
                                    vtext: 'ROMALILAR 8:28 (TCL02)<br/><br/>Tanrı\'nın, kendisini sevenlerle, amacı uyarınca çağrılmış olanlarla birlikte her durumda iyilik için etkin olduğunu biliriz.',
                                    leaf: true
                                },
                                {
                                    text: '2Ko.4:16-18',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/2Ko4_16-18.mp3',
                                    vtext: '2.KORİNTLİLER 4:16-18 (TCL02)<br/><br/>Bu nedenle cesaretimizi yitirmeyiz. Her ne kadar dış varlığımız harap oluyorsa da, iç varlığımız günden güne yenileniyor. Çünkü geçici, hafif sıkıntılarımız bize, ağırlıkta hiçbir şeyle karşılaştırılamayacak kadar büyük, sonsuz bir yücelik kazandırmaktadır. Gözlerimizi görünen şeylere değil, görünmeyenlere çeviriyoruz. Çünkü görünenler geçicidir, görünmeyenlerse sonsuza dek kalıcıdır.',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'Tanrı\'nın tesellisi',
                            items: [
                                {
                                    text: '2Ko.1:3-11',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/2Ko1_3-11.mp3',
                                    vtext: '2.KORİNTLİLER 1:3-11 (TCL02)<br/><br/>Her türlü tesellinin kaynağı olan Tanrı\'ya, merhametli Baba\'ya, Rabbimiz İsa Mesih\'in Tanrısı ve Babası\'na övgüler olsun! Kendisinden aldığımız teselliyle her türlü sıkıntıda olanları teselli edebilmemiz için bizi bütün sıkıntılarımızda teselli ediyor. Çünkü Mesih\'in acılarını nasıl büyük ölçüde çekiyorsak, Mesih sayesinde büyük teselli de buluyoruz.',
                                    leaf: true
                                },
                                {
                                    text: 'Vah.21:4',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Vah21_4.mp3',
                                    vtext: 'Scripture verse missing',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'doğruluk ve tanıklık üzerine',
                            items: [
                                {
                                    text: 'Mat.5:10-13',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Mat5_10-13.mp3',
                                    vtext: 'MATTA 5:10-13 (TCL02)<br/><br/>Ne mutlu doğruluk uğruna zulüm görenlere! Çünkü Göklerin Egemenliği onlarındır. \'Benim yüzümden insanlar size sövüp zulmettikleri, yalan yere size karşı her türlü kötü sözü söyledikleri zaman ne mutlu size! Sevinin, sevinçle coşun! Çünkü göklerdeki ödülünüz büyüktür. Sizden önce yaşayan peygamberlere de böyle zulmettiler.\'',
                                    leaf: true
                                },
                                {
                                    text: 'Mat.24:9',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Mat24_9.mp3',
                                    vtext: 'MATTA 24:9 (TCL02)<br/><br/>O zaman sizi sıkıntıya sokacak, öldürecekler. Benim adımdan ötürü bütün uluslar sizden nefret edecek.',
                                    leaf: true
                                },
                                {
                                    text: 'Yuh.15:18-25',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Yuh15_18-25.mp3',
                                    vtext: 'Scripture verse missing',
                                    leaf: true
                                },
                                {
                                    text: 'Vah.6:9-11',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Vah6_9-11.mp3',
                                    vtext: 'Scripture verse missing',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'Mesih\'in örneği',
                            items: [
                                {
                                    text: 'İbr.5:7-9',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Ibr5_7-9.mp3',
                                    vtext: 'Scripture verse missing',
                                    leaf: true
                                }
                            ]
                        }
                    ]
                },
                {
                    text: 'açgözlülük',
                    leaf: true
                },
                {
                    text: 'adalet',
                    leaf: true
                }
            ]
        },
        model: 'Fihrist.model.Nested',
        storeId: 'NestedTopics',
        defaultRootProperty: 'items'
    }
});