/*
 * File: app/view/MainPortrait.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fihrist.view.MainPortrait', {
    extend: 'Ext.tab.Panel',

    config: {
        items: [
            {
                xtype: 'container',
                iconCls: 'arrow_down',
                items: [
                    {
                        xtype: 'container',
                        height: '100%',
                        layout: {
                            type: 'vbox'
                        },
                        scrollable: 'vertical',
                        items: [
                            {
                                xtype: 'titlebar',
                                docked: 'top'
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                itemId: 'horzholder',
                                layout: {
                                    type: 'hbox'
                                },
                                scrollable: true,
                                items: [
                                    {
                                        xtype: 'list',
                                        flex: 1,
                                        itemId: 'topics',
                                        itemTpl: [
                                            '<div>{Name}</div>'
                                        ],
                                        store: 'topics'
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1.5,
                                        itemId: 'concepts',
                                        tpl: [
                                            '{Text}'
                                        ],
                                        layout: {
                                            type: 'fit'
                                        },
                                        items: [
                                            {
                                                xtype: 'audio',
                                                itemId: 'vmp3'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                iconCls: 'team'
            },
            {
                xtype: 'container',
                iconCls: 'settings'
            }
        ],
        tabBar: {
            docked: 'bottom',
            ui: 'light'
        },
        listeners: [
            {
                fn: 'onMylistItemTap',
                event: 'itemtap',
                delegate: '#topics'
            }
        ]
    },

    onMylistItemTap: function(dataview, index, target, record, e, eOpts) {
        //alert('tap: ' + record.data.TextURL);
        var container = dataview.up('#horzholder');
        var panel = container.down('#concepts');
        panel.removeAll();

        var vMp3 = panel.getComponent('vmp3');

        var text = '';
        var subtopic = record.data.subtopic;

        if ( subtopic ) {
            var subList = subtopic.split(',');

            var subTopics = Ext.getStore('subtopics');
            var verses = Ext.getStore('verses');

            for (i = 0; i < subList.length; i++) {
                //text = text + ' ' + subList[i];
                rec = subTopics.findRecord('UID', subList[i]);
                if (rec) {
                    //text = text + '--' + rec.data.text + '<br />';
                    var myPanel = Ext.create('Ext.Panel', {
                        html: '<strong>' + rec.data.text + '</strong><br />'
                    });
                    panel.add( {xtype: 'panel', padding: 10, items: [myPanel] });


                    var verseListing = rec.data.verse;
                    var verseList = verseListing.split(',');

                    for (y = 0; y < verseList.length; y++) {

                        vrec = verses.findRecord('UID', verseList[y]);
                        if (vrec) {
                            // text = text + ' ----- ' + verseList[y];

                            var vText = vrec.data.text;
                            var vURL = vrec.data.MP3URL;
                            //text = text + '------- <a href="' + vURL + '">' + vText + '</a><br />';
                            var button = Ext.create('Ext.Button', {
                                text: vText,
                                itemId: vURL,
                                iconCls: 'arrow_right',
                                iconMask: true,
                                width: 200,
                                handler : function(b,e){
                                    alert('tap: ' + this.getItemId());
                                    vMp3.setUrl( this.getItemId() );
                                    vMp3.play();

                                    /* var vMp3 = Ext.create('Ext.Panel', {
                                    modal      : true,
                                    hideOnMaskTap: true,
                                    autoDestroy: true,
                                    centered   : true,
                                    border: 0,
                                    scrollable : false,
                                    width      : '70%',
                                    height     : '70%',
                                    layout     : {
                                    type  : 'vbox',
                                    align : 'stetch'
                                    },
                                    items      : [{
                                    xtype:'fieldset',
                                    title: 'some title',
                                    items:[{
                                    xtype:'audio',
                                    url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Mat5_10-13.mp3',
                                    title:'Sample MP3',
                                    autoDestroy: true,
                                    autoResume: false,
                                    enableControls: false,
                                    autoPause: true
                                    },{
                                    xtype: 'button',
                                    text: 'Play',
                                    iconCls: 'arrow_right',
                                    iconMask: true,
                                    autoDestroy: true,
                                    width: 50,
                                    handler: function(b,e) {
                                    var audio = this.getParent().down('audio');
                                    if (audio.isPlaying()) {
                                    audio.pause();
                                    b.setText('Play audio');
                                    b.setIconCls('arrow_right');
                                    } else {
                                    audio.play();
                                    b.setText('Pause Audio');
                                    b.setIconCls('delete');
                                    }
                                    if (b.isHidden()) {
                                    audio.pause();
                                    alert('audio is hidden');
                                    };
                                    }
                                    },{
                                    xtype : 'slider',
                                    width: '30%',
                                    autoDestroy: true,
                                    listeners: [{dragstart : 'onSliderDragStart'},{drag : 'onSliderDrag'}]
                                    }]
                                    }]
                                    });
                                    container.add( [vMp3] );

                                    function onSliderDrag(slider, thumb, value) {
                                    alert('onsliderdrag');
                                    var audioCmp = this.down('audio'),
                                    duration = audioCmp.element.dom.childNodes[0].duration;

                                    value = value[0];

                                    audioCmp.setCurrentTime((value / 100) * duration);
                                    audioCmp.play();
                                    }

                                    */

                                }
                            });
                            panel.add({ xtype: 'container', padding: 10, items: [button] });



                        } else {
                            text = text + '---+-- No verse found';
                        }

                    }
                }else{
                    text = text + '-- rec not found <br />';

                }
            }

        } else {
            text = 'No subtopics found';

        }


        panel.setData({ Text: text });
    }

});