/*
 * File: app/view/MyPanel3.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fihrist.view.MyPanel3', {
    extend: 'Ext.Panel',

    config: {
        items: [
            {
                xtype: 'audio',
                hidden: true,
                itemId: 'mp3player',
                url: 'http://www.kutsalkitap.org/fihrist/Fihrist/sesdosyalar/Rom8_18-22.mp3'
            },
            {
                xtype: 'button',
                itemId: 'controls',
                iconAlign: 'center',
                iconCls: 'arrow_right'
            },
            {
                xtype: 'component',
                itemId: 'versetext',
                ui: 'light'
            }
        ],
        listeners: [
            {
                fn: 'onControlsTap',
                event: 'tap',
                delegate: '#controls'
            }
        ]
    },

    onControlsTap: function(button, e, eOpts) {
        var audio = this.getParent().down('audio');
        if (audio.isPlaying()) {
            audio.pause();
            button.setText('Play audio');
        } else {
            audio.play();
            button.setText('Pause Audio');
        }
    }

});