/*
 * File: app/store/Topics.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Fihrist.store.Topics', {
    extend: 'Ext.data.Store',
    alias: 'store.topics',

    requires: [
        'Fihrist.model.Topic'
    ],

    config: {
        data: [
            {
                UID: 'T1',
                Name: 'acı',
                subtopic: 'S1,S2,S3,S4,S5,S6,S7'
            },
            {
                UID: 'T2',
                Name: 'açgözlülük',
                subtopic: ''
            },
            {
                UID: 'T3',
                Name: 'adalet',
                subtopic: ''
            },
            {
                UID: 'T4',
                Name: 'aile',
                subtopic: ''
            },
            {
                UID: 'T5',
                Name: 'aklanma',
                subtopic: ''
            }
        ],
        model: 'Fihrist.model.Topic',
        storeId: 'topics'
    }
});